In [1]:
import pandas as pd
import numpy as np

In [3]:
# Load datasets
sales = pd.read_csv("./sales 1.csv")
customers = pd.read_json("./customers.json")
products = pd.read_csv("./products.csv")

In [4]:
# View data
print(sales.head())

                                 SaleID  ProductID CustomerID  SalesAmount  \
0  c0078cd1-3ddc-439a-b41d-7498e8e75e62       1020      C0460      1639.10
1  be8532af-16b7-432c-a13d-4c6e6836d12d       1029      C0198       186.11
2  8666f277-cc58-4fde-9d58-697da9e040f2       1012      C0524      1712.72
3  383e0a2b-7e00-454e-a269-b2f73ecd33f2       1016      C0285          NaN
4  d9a7f974-9572-48dd-aa36-3f96b280dfc7       1021      C0369        66.36

   Quantity            Timestamp
0      18.0  2024-08-09T20:21:00
1      42.0  2024-11-28T05:01:00
2      49.0  2024-10-13T00:36:00
3      50.0  2024-07-06T23:39:00
4      21.0  2024-06-08T19:58:00

In [5]:
print(customers.head())

  CustomerID FirstName LastName Gender      Region          SSN
0      C0001   Gregory   Miller      M        Ohho    082573197
1      C0002    Marvin      NaN   male  california  309-6256-21
2      C0003   Gregory    Smith   Male   New Yorkk    407071725
3      C0004    Edward    Davis   male        Ohho  948.18.5740
4      C0005  Reginald   Dawson   male       Texas  975.72.3056

In [6]:
print(products.head())

   ProductID      ProductName         Category
0       1000  Washing Machine  Home Appliances
1       1001     Refrigerator  Home Appliances
2       1002          Blender  Home Appliances
3       1003        Microwave  Home Appliances
4       1004   Vacuum Cleaner  Home Appliances

In [11]:
# Dataset information
sales.info()
print("______________________")
customers.info()
print("______________________")
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SaleID       10000 non-null  str
 1   ProductID    10000 non-null  int64
 2   CustomerID   10000 non-null  str
 3   SalesAmount  9503 non-null   float64
 4   Quantity     9887 non-null   float64
 5   Timestamp    10000 non-null  str
dtypes: float64(2), int64(1), str(3)
memory usage: 468.9 KB
______________________
<class 'pandas.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  1100 non-null   str
 1   FirstName   1100 non-null   str
 2   LastName    780 non-null    str
 3   Gender      1100 non-null   str
 4   Region      1031 non-null   str
 5   SSN         1100 non-null   str
dtypes: str(6)
memory usage: 51.7 KB
______________________
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    50 non-null     int64
 1   ProductName  50 non-null     str
 2   Category     50 non-null     str
dtypes: int64(1), str(2)
memory usage: 1.3 KB

In [10]:
# Missing values
print(sales.isnull().sum())
print("______________________")
print(customers.isnull().sum())
print("______________________")
print(products.isnull().sum())

SaleID           0
ProductID        0
CustomerID       0
SalesAmount    497
Quantity       113
Timestamp        0
dtype: int64
______________________
CustomerID      0
FirstName       0
LastName      320
Gender          0
Region         69
SSN             0
dtype: int64
______________________
ProductID      0
ProductName    0
Category       0
dtype: int64

In [12]:
# Duplicate records
print("Sales Duplicates:", sales.duplicated().sum())
print("______________________")
print("Customer Duplicates:", customers.duplicated().sum())
print("______________________")
print("Product Duplicates:", products.duplicated().sum())

Sales Duplicates: 0
______________________
Customer Duplicates: 100
______________________
Product Duplicates: 0

Missing Sales Amount

In [14]:
sales["SalesAmount"] = sales["SalesAmount"].fillna(
sales["SalesAmount"].median()
)

In [15]:
print(sales.isnull().sum())
print("______________________")

SaleID           0
ProductID        0
CustomerID       0
SalesAmount      0
Quantity       113
Timestamp        0
dtype: int64
______________________

Missing Quantity

In [16]:
sales["Quantity"] = sales["Quantity"].fillna(
    sales["Quantity"].median()
)

In [17]:
print(sales.isnull().sum())

SaleID         0
ProductID      0
CustomerID     0
SalesAmount    0
Quantity       0
Timestamp      0
dtype: int64

In [18]:
customers.head(3)

  CustomerID FirstName LastName Gender      Region          SSN
0      C0001   Gregory   Miller      M        Ohho    082573197
1      C0002    Marvin      NaN   male  california  309-6256-21
2      C0003   Gregory    Smith   Male   New Yorkk    407071725

##Gender Standardization

In [19]:
customers["Gender"] = customers["Gender"].replace({
    "M":"Male",
    "Male ":"Male",
    "F":"Female",
    "Female ":"Female"
})

In [27]:
customers.head(5)

  CustomerID FirstName LastName Gender      Region          SSN
0      C0001   Gregory   Miller   Male        Ohio    082573197
1      C0002    Marvin      NaN   male  california  309-6256-21
2      C0003   Gregory    Smith   Male    New York    407071725
3      C0004    Edward    Davis   male        Ohio  948.18.5740
4      C0005  Reginald   Dawson   male       Texas  975.72.3056

In [26]:
customers.nunique()

CustomerID    1000
FirstName      318
LastName       400
Gender           4
Region           6
SSN           1000
dtype: int64

Region Standardization

In [28]:
customers["Region"] = customers["Region"].replace({
    "Ohho":"Ohio",
    "OHIO":"Ohio",
    "NY":"New York",
    "New Yorkk":"New York",
    "Nw York":"New York"
})

In [29]:
customers.head(5)

  CustomerID FirstName LastName Gender      Region          SSN
0      C0001   Gregory   Miller   Male        Ohio    082573197
1      C0002    Marvin      NaN   male  california  309-6256-21
2      C0003   Gregory    Smith   Male    New York    407071725
3      C0004    Edward    Davis   male        Ohio  948.18.5740
4      C0005  Reginald   Dawson   male       Texas  975.72.3056

In [30]:
customers["Region"] = customers["Region"].fillna("Unknown")

In [31]:
sales = sales.drop_duplicates()
customers = customers.drop_duplicates()
products = products.drop_duplicates()

In [32]:
sales.count()

SaleID         10000
ProductID      10000
CustomerID     10000
SalesAmount    10000
Quantity       10000
Timestamp      10000
dtype: int64

In [38]:
print(sales["SalesAmount"].min())
print(sales["SalesAmount"].max())
sales["SalesAmount"].head()

50.18
79783.4

0    1639.10
1     186.11
2    1712.72
3    1015.07
4      66.36
Name: SalesAmount, dtype: float64

In [40]:
Q1 = sales["SalesAmount"].quantile(0.25)
Q3 = sales["SalesAmount"].quantile(0.75)

In [41]:
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = sales[
    (sales["SalesAmount"] < lower) |
    (sales["SalesAmount"] > upper)
]

print(outliers.shape)

(79, 6)

In [44]:
print(outliers)

                                    SaleID  ProductID CustomerID  SalesAmount  \
179   f88e997a-65bc-4e3c-966f-7d8796f83c5d       1029      C0256     40458.92
483   f01892e4-149f-40a1-95e7-fda3df4d0bc5       1032      C0349     64357.03
542   b2a09161-e694-47ca-bbc5-cc74e30b3121       1045      C0064     51858.11
690   d2f8521f-9fde-435a-8a50-2ea238052ab2       1047      C0041     21176.88
787   60337106-faa0-48a5-b55d-75db312c71ab       1004      C0426     61821.50
...                                    ...        ...        ...          ...
9601  2fcaa635-5d6a-4bd5-bdc1-876b86c444da       1030      C0144     61695.49
9805  dec7ebdc-ea35-4dcb-9e97-688b640307b1       1034      C0122     59637.24
9927  bae96876-7a12-489a-91d3-3d8792b91c3e       1030      C0269     76993.72
9937  56aa51cf-b202-4a01-8f5e-5b5a335cebaf       1039      C0051     77834.11
9957  45f3cc21-5244-4dda-8f0d-c993de9a53c4       1005      C0809     27261.56

      Quantity            Timestamp
179       26.0  2024-08-16T13:23:00
483       39.0  2024-08-05T01:31:00
542       33.0  2024-07-19T23:36:00
690        5.0  2024-11-13T04:03:00
787       15.0  2024-11-09T11:31:00
...        ...                  ...
9601      20.0  2024-10-11T04:00:00
9805      29.0  2024-10-22T00:07:00
9927      22.0  2024-11-13T02:55:00
9937      46.0  2024-09-11T01:14:00
9957       3.0  2024-08-06T09:07:00

[79 rows x 6 columns]

In [45]:
sales["Timestamp"] = pd.to_datetime(
    sales["Timestamp"]
)

sales["Year"] = sales["Timestamp"].dt.year

sales["Month"] = sales["Timestamp"].dt.month

sales["MonthName"] = sales["Timestamp"].dt.month_name()

In [46]:
print(sales["Timestamp"])

0      2024-08-09 20:21:00
1      2024-11-28 05:01:00
2      2024-10-13 00:36:00
3      2024-07-06 23:39:00
4      2024-06-08 19:58:00
               ...
9995   2024-10-06 18:50:00
9996   2024-08-21 07:47:00
9997   2024-09-16 16:21:00
9998   2024-06-07 02:21:00
9999   2024-10-02 22:52:00
Name: Timestamp, Length: 10000, dtype: datetime64[us]

In [48]:
sales.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,Year,Month,MonthName
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09 20:21:00,2024,8,August
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,2024,11,November
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,2024,10,October
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,1015.07,50.0,2024-07-06 23:39:00,2024,7,July
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08 19:58:00,2024,6,June

In [49]:
sales.to_csv(
    "sales_cleaned.csv",
    index=False
)

customers.to_csv(
    "customers_cleaned.csv",
    index=False
)

products.to_csv(
    "products_cleaned.csv",
    index=False
)